POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "James Wiseman",
"important": true,
"id": 10,
"weight": 190
}

###

GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/242476596